modules:
  http_ipv4_2xx:
    prober: http
    http:
      preferred_ip_protocol: ipv4
      ip_protocol_fallback: false
      fail_if_not_ssl: true
  http_ipv4_401:
    prober: http
    http:
      preferred_ip_protocol: ipv4
      ip_protocol_fallback: false
      fail_if_not_ssl: true
      valid_status_codes:
        - 401
  http_ipv6_2xx:
    prober: http
    http:
      preferred_ip_protocol: ipv6
      ip_protocol_fallback: false
      fail_if_not_ssl: true
  http_ipv6_401:
    prober: http
    http:
      preferred_ip_protocol: ipv6
      ip_protocol_fallback: false
      fail_if_not_ssl: true
      valid_status_codes:
        - 401
  tcp_connect:
    prober: tcp
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
        - send: "SSH-2.0-blackbox-ssh-check"
  icmp:
    prober: icmp
