# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  server_host: 127.0.0.1
# Text to speech
tts:
  - platform: google_translate
nest:
  client_id: !secret client_id
  client_secret: !secret client_secret
  project_id: !secret project_id

automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
