# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
nest:
  client_id: !secret client_id
  client_secret: !secret client_secret
  project_id: !secret project_id

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
