# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
sonos:
  media_player:
    hosts:
      - 192.168.1.9 # Living Room Right
      - 192.168.1.40 # Living Room Left
      - 192.168.1.48 # Bedroom Right
      - 192.168.1.54 # Bathroom
      - 192.168.1.73 # Kitchen
      - 192.168.1.80 # Living Room Sub
      - 192.168.1.223 # Sonos Move
      - 192.168.1.227 # Dining Room
      - 192.168.1.240 # Living Room Arc
      - 192.168.1.246 # Bedroom Left
    advertise_addr: 192.168.1.45

# Text to speech
tts:
  - platform: google_translate
ffmpeg:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
