repos:
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt
      - id: deno-lint
      # TODO: uncomment if/when I add tests
      # - id: deno-test
  - repo: https://github.com/stackrox/kube-linter
    rev: v0.6.5
    hooks:
      - id: kube-linter
        args: ["turing/dist/", "apps/templates/"]
    # TODO: sandbox this
  - repo: local
    hooks:
      - id: run
        name: build k8s manifest
        entry: bash -c 'cd turing && deno task build'
        language: system
        types: [ts]
        pass_filenames: false
