---
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    env_file:
      - config/vars.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    volumes:
      - /lib/modules:/lib/modules
      - ./config/wireguard:/config
  homeassistant:
    container_name: homeassistant
    env_file:
      - config/vars.env
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 1400:1400 # Sonos
      # homekit
      - 5353:5353
      - 21063:21063
      - 21064:21064
      - 21065:21065
      - 21066:21066
    restart: unless-stopped
    volumes:
      - homeassistant-config:/config
      - ./config/homeassistant/configuration.yaml:/config/configuration.yaml:Z
  mdns_repeater:
    container_name: mdns_repeater
    image: jdbeeler/mdns-repeater
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      EXTERNAL_INTERFACE: eno1
      DOCKER_NETWORK_NAME: servers
      USE_MDNS_REPEATER: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
