---
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    env_file:
      - config/vars.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    volumes:
      - /lib/modules:/lib/modules
      - ./config/wireguard:/config
  mdns_repeater:
    container_name: mdns_repeater
    image: jdbeeler/mdns-repeater
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      EXTERNAL_INTERFACE: eno1
      DOCKER_NETWORK_NAME: servers
      USE_MDNS_REPEATER: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
