apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: nvidia
spec:
  project: default
  source:
    repoURL: "https://nvidia.github.io/k8s-device-plugin"
    targetRevision: 0.14.3
    chart: nvdp
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvidia
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
