---
services:
  caddy_tailscale:
    container_name: caddy_tailscale
    depends_on:
      - tailscale
    build: config/caddy
    env_file:
      - vars.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 100.88.20.114:80:80
      - 100.88.20.114:443:443
      - fd7a:115c:a1e0:ab12:4843:cd96:6258:1472:80:80
      - fd7a:115c:a1e0:ab12:4843:cd96:6258:1472:443:443
    volumes:
      - caddy-tailscale-config:/config:Z
      - caddy-tailscale-data:/data:Z
      - ./static/tailscale.html:/srv/index.html:Z
      - ./config/caddy/tailscale.Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./config/credentials:/root/.aws/credentials:ro,Z
    restart: unless-stopped
  geoip-updater:
    container_name: geoip-updater
    env_file:
      - vars.env
    image: crazymax/geoip-updater:latest
    restart: unless-stopped
    volumes:
      - rtorrent-data:/data
  prometheus:
    container_name: prometheus
    env_file:
      - vars.env
    extra_hosts:
      - host.docker.internal:host-gateway
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - prometheus-config:/etc/prometheus/
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
  rtorrent:
    container_name: rtorrent
    depends_on:
      - tailscale
    environment:
      WAN_IP: 158.69.122.44
    env_file:
      - vars.env
    image: crazymax/rtorrent-rutorrent:latest
    ports:
      - 50000:50000
      - 6881:6881
      - 100.88.20.114:8000:8000
      - fd7a:115c:a1e0:ab12:4843:cd96:6258:1472:8000:8000
    restart: unless-stopped
    ulimits:
      nofile:
        hard: 40000
        soft: 32000
      nproc: 65535
    volumes:
      - rtorrent-data:/data
      - rtorrent-temp:/downloads/temp
      - /home/debian/syncthing/Torrents:/downloads/complete:Z
  speedtest:
    container_name: speedtest
    env_file:
      - vars.env
    image: jraviles/prometheus_speedtest:latest
    restart: unless-stopped
  syncthing:
    container_name: syncthing
    env_file:
      - vars.env
    hostname: syncthing
    image: syncthing/syncthing:latest
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    volumes:
      - syncthing-config:/var/syncthing/
      - /home/debian/syncthing:/syncthing:Z
  syncthing_exporter:
    container_name: syncthing_exporter
    env_file:
      - vars.env
    environment:
      SYNCTHING_TOKEN: JHtHwiK7SWFLhnA4C3WrNSLYE6XjkoQT
      SYNCTHING_URI: http://syncthing:8384/
    image: f100024/syncthing_exporter:latest
    restart: unless-stopped
  tailscale:
    command: tailscaled
    container_name: tailscale
    env_file:
      - vars.env
    image: tailscale/tailscale
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
  volumerize:
    container_name: volumerize
    env_file:
      - vars.env
    environment:
      VOLUMERIZE_CONTAINERS: syncthing grafana prometheus loki
      VOLUMERIZE_FULL_IF_OLDER_THAN: 28D
      VOLUMERIZE_JOBBER_TIME: 0 0 4 * * *
      VOLUMERIZE_SOURCE: /source
      VOLUMERIZE_TARGET: file:///target
    image: blacklabelops/volumerize:1.7.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volumerize-cache:/volumerize-cache
      - /home/debian/backup:/target:Z
      - syncthing-config:/source/syncthing-config:ro
      - grafana-data:/source/grafana-data:ro
      - prometheus-config:/source/prometheus-config:ro
      - prometheus-data:/source/prometheus-data:ro
      - loki-data:/source/loki-data:ro
      - rtorrent-data:/source/rtorrent-data:ro
version: "3.8"
volumes:
  grafana-data: null
  loki-data: null
  prometheus-config: null
  prometheus-data: null
  rtorrent-data: null
  rtorrent-temp: null
  syncthing-config: null
  volumerize-cache: null
  caddy-tailscale-config: null
  caddy-tailscale-data: null
