apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://1password.github.io/connect-helm-charts/"
    targetRevision: 1.14.0
    chart: connect
    valuesObject:
      operator:
        autoRestart: true
        create: true
        pollingInterval: 60
  destination:
    server: "https://kubernetes.default.svc"
    namespace: 1password
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
