apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: 1password
spec:
  project: default
  source:
    repoURL: 'https://1password.github.io/connect-helm-charts/'
    targetRevision: 1.14.0
    chart: connect
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 1password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
