apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shepherdjerred/servers'
    path: argocd/dist/
    targetRevision: sj/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
