server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd-journal
    journal:
      labels:
        job: default/systemd-journal
      path: /var/log/journal
    relabel_configs:
      - source_labels:
          - __journal_container_name
        target_label: container_name
      - source_labels:
          - __journal_container_id_full
        target_label: container_id
      - source_labels:
          - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
          - __journal__hostname
        target_label: hostname
      - source_labels:
          - __journal_syslog_identifier
        target_label: syslog_identifier
