# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homekit:
  - name: HA1
    advertise_ip: 192.168.1.45
    port: 21063
    filter:
      include_domains:
        - climate
        - cover
        - fan
        - humidifier
        - alarm_control_panel
        - remote
        - water_heater
        - sensor
        - switch
        - device_tracker
        - binary_sensor
        - input_select
      exclude_entities:
        - sensor.front_door_battery_2
        - binary_sensor.front_door_ding
        - binary_sensor.front_door_motion
      exclude_entity_globs:
        - binary_sensor.*entertainment_configuration
        - switch.adaptive_lighting_*
  - name: HA2
    advertise_ip: 192.168.1.45
    port: 21064
    filter:
      include_domains:
        - light
  - name: Doorbell
    advertise_ip: 192.168.1.45
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - camera.front_door
        # - sensor.front_door_battery_2
        # - binary_sensor.front_door_ding
        # - binary_sensor.front_door_motion
    entity_config:
      camera.front_door:
        linked_doorbell_sensor: binary_sensor.front_door_ding
        linked_motion_sensor: binary_sensor.front_door_motion
        linked_battery_sensor: sensor.front_door_battery_2
  - name: HA4
    advertise_ip: 192.168.1.45
    port: 21066
    mode: accessory
    filter:
      include_domains:
        - lock

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
sonos:
  media_player:
    advertise_addr: 192.168.1.45

# Text to speech
tts:
  - platform: google_translate
ffmpeg:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
