scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: nginx_public
    static_configs:
      - targets:
          - nginx_public_exporter:9113
  - job_name: nginx_tailscale
    static_configs:
      - targets:
          - nginx_tailscale_exporter:9113
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080
  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
