scrape_configs:
  - job_name: nvidia_exporter
    static_configs:
      - targets:
          - nvidia_exporter:9400
  - job_name: syncthing_exporter
    static_configs:
      - targets:
          - syncthing_exporter:9093
  - job_name: "blackbox_ssh_ipv4"
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
          - tailscale.zeus.shepherdjerred.com:22
          - public.zeus.shepherdjerred.com:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "blackbox_ssh_ipv6"
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
          - tailscale.zeus.shepherdjerred.com:22
          - public.zeus.shepherdjerred.com:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "blackbox_http_ipv6_2xx"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://influxdb.tailscale.zeus.shepherdjerred.com:443
          - https://overseerr.tailscale.zeus.shepherdjerred.com:443
          - https://homeassistant.tailscale.zeus.shepherdjerred.com:443
          - https://tailscale.zeus.shepherdjerred.com:443
          - https://tailscale.zeus.shepherdjerred.com/tautulli:443
          - https://tailscale.zeus.shepherdjerred.com/jackett:443
          - https://tailscale.zeus.shepherdjerred.com/sonarr:443
          - https://tailscale.zeus.shepherdjerred.com/radarr:443
          - https://tailscale.zeus.shepherdjerred.com:443
          - https://public.zeus.shepherdjerred.com:443
          - https://overseerr.public.zeus.shepherdjerred.com:443
          - https://homeassistant.public.zeus.shepherdjerred.com:443
          - https://plex.tailscale.zeus.shepherdjerred.com/identity:443
          - https://plex.public.zeus.shepherdjerred.com/identity:443
          - https://tailscale.zeus.shepherdjerred.com/syncthing:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "blackbox_http_ipv4_2xx"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://influxdb.tailscale.zeus.shepherdjerred.com:443
          - https://overseerr.tailscale.zeus.shepherdjerred.com:443
          - https://homeassistant.tailscale.zeus.shepherdjerred.com:443
          - https://tailscale.zeus.shepherdjerred.com:443
          - https://tailscale.zeus.shepherdjerred.com/tautulli:443
          - https://tailscale.zeus.shepherdjerred.com/jackett:443
          - https://tailscale.zeus.shepherdjerred.com/sonarr:443
          - https://tailscale.zeus.shepherdjerred.com/radarr:443
          - https://tailscale.zeus.shepherdjerred.com:443
          - https://public.zeus.shepherdjerred.com:443
          - https://overseerr.public.zeus.shepherdjerred.com:443
          - https://homeassistant.public.zeus.shepherdjerred.com:443
          - https://plex.tailscale.zeus.shepherdjerred.com/identity:443
          - https://plex.public.zeus.shepherdjerred.com/identity:443
          - https://tailscale.zeus.shepherdjerred.com/syncthing:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: speedtest
    metrics_path: /probe
    scrape_interval: 5m
    scrape_timeout: 5m
    static_configs:
      - targets:
          - speedtest:9516
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: nginx_public
    static_configs:
      - targets:
          - nginx_public_exporter:9113
  - job_name: nginx_tailscale
    static_configs:
      - targets:
          - nginx_tailscale_exporter:9113
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080
  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
