scrape_configs:
  - job_name: syncthing_exporter
    static_configs:
      - targets:
          - syncthing_exporter:9093
  - job_name: speedtest
    metrics_path: /probe
    scrape_interval: 5m
    scrape_timeout: 5m
    static_configs:
      - targets:
          - speedtest:9516
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
