scrape_configs:
  - job_name: syncthing_exporter
    static_configs:
      - targets:
          - syncthing_exporter:9093
  - job_name: "blackbox_ssh"
    metrics_path: /probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
          - ts.persephone.sjer.red
          - public.persephone.sjer.red
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "blackbox_http_401"
    metrics_path: /probe
    params:
      module: [http_401]
    static_configs:
      - targets:
          - https://ts.persephone.sjer.red/syncthing
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "blackbox_http_2xx"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://ts.persephone.sjer.red
          - https://public.persephone.sjer.red
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: speedtest
    metrics_path: /probe
    scrape_interval: 5m
    scrape_timeout: 5m
    static_configs:
      - targets:
          - speedtest:9516
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080
  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
