name: CDK CI/CD

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./cdk

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1.0.3
      - name: Lint
        run: earthly --ci --push +lint
      - name: Deploy
        run: earthly --ci --push +deploy
